//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loguate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_producto_empresa
    {
        public int ID_Producto { get; set; }
        public int ID_Empresas { get; set; }
    }
}
