//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loguate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public long ID_Contacto { get; set; }
        public string nombreContacto { get; set; }
        public string telefonoContacto { get; set; }
        public string emailContacto { get; set; }
    }
}
