//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace Loguate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Productos = new HashSet<Producto>();
            this.cliente = new HashSet<Cliente>();
            
        }

        public long ID_Empresas { get; set; }
        [DisplayName("Nombre")]
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        [DisplayName("Cliente")]
        public long ID_Clientes { get; set; }
        [DisplayName("Contacto")]
        public string nombreContacto { get; set; }
        [DisplayName("Telefono")]
        public string telefonoContacto { get; set; }
        [DisplayName("Correo")]
        public string correoContacto { get; set; }
        [DisplayName("Producto")]
        public string nombreProducto { get; set; }



        public IEnumerable<Producto> prodductos { get; set; }
        public IEnumerable<Cliente> clientes { get; set; }

        public ICollection<Cliente> cliente{ get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Productos { get; set; }
    }
}
