//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace Loguate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormProyecto
    {
        public IEnumerable<Consultor> consultors;
        public IEnumerable<AreaModulo> areaModulos;
        public IEnumerable<Herramienta> herramientas;
        public IEnumerable<Empresa> empresas;
        public IEnumerable<Producto> productos;
        public IEnumerable<Tipo> tipos;
        public IEnumerable<Cliente> clientes;
        public long ID_Proyectos { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Version { get; set; }
        public string Herramientas { get; set; }
        public string Clientes { get; set; }
        public string Empresas { get; set; }
        public string AreaModulo { get; set; }
        public string Productos { get; set; }
        public string Consultor_Levantamiento { get; set; }
        public Nullable<System.DateTime> Fecha_Levantamiento { get; set; }
        public Nullable<System.DateTime> Fecha_inicio_desarrollo { get; set; }
        public Nullable<System.DateTime> fecha_calidad { get; set; }
        public string comentario { get; set; }
        public string Consultor_Dev { get; set; }
        public Nullable<System.DateTime> Fecha_Entrega { get; set; }
        public string Atachar_Archivo { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public FormProyecto()
        {
            Atachar_Archivo = "~/AppFiles/Images/default.png";
        }
    }
}
